### ISSUE TITLE
:f does more than flattening

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#14]
While the document says "flatten the array once", current implementation sums elements if the first element of the array is a number, illustrated by [this](https://staxlang.xyz/#c=%3Af%7C%60&i=[3+4+[5+[6]]]&a=1).

**Comment by tomtheisen** [comment]
I can see what you're describing.  The documentation couldn't be correct in this case, since this array *can't* be flattened once.  So here's what I think needs to be done.

1.  Determine the best behavior.
2.  If it's different than the current behavior, implement it.
3.  Document the actual behavior.

The hardest part of this seems to be number 1.  Any opinions?  I kind of like `[3 4 5 [6]]` for your test case.

**Comment by William8915** [comment]
I also assume it to be `[3 4 5 [6]]`.

**Comment by joshudson** [comment]
My personal opinion is that [3 4 5]f -> [3 4 5]

**Comment by tomtheisen** [comment]
It seems to be a concensus then.  It will leave alone non arrays. It will unwrap arrays once.

**Comment by tomtheisen** [comment]
Fixed in 9dfcc40aea7c40dea717ac474ab7c29bd9f47668.
