### ISSUE TITLE
License Exists

### ISSUE THREAD

**Issue by A-ee** [tomtheisen/stax#31]
For the content in LICENSE.md, it allows others to do anything they want. There is an [existing](https://choosealicense.com/licenses/wtfpl/) license for that.

**Comment by tomtheisen** [comment]
I kind of like my current one since it seems even more ambiguous than WTFPL.  Organizations with legal departments hate ambiguity.  But I've got an open mind.  Is there some advantage to using an established license?  I'm necessarily trying to encourage adoption or redistribution or whatever, like I imagine a lot of projects are.

You might be interested in the string packing, as it seems to align pretty closely with ECOM.  FWIW, you can use any algorithms, code, data, or anything else from this project.  It would be cool if you gave me a credit, but if you're set against it I'm not going to make an issue out of it.

The string literal packing algorithm has two implementations, whose entry points are here.:

 * Typescript: https://github.com/tomtheisen/stax/blob/master/StaxLang.JS/huffmancompression.ts
 * C#: https://github.com/tomtheisen/stax/blob/master/StaxLang.Interpreter/HuffmanCompressor.cs
